### ISSUE TITLE
Documentation on readthedocs is out of date

### ISSUE THREAD

**Issue by tochev** [django-cms/django-sekizai#100]
The documentation on https://django-sekizai.readthedocs.io/en/latest/ is out of date.

The link is found in the [README](https://github.com/django-cms/django-sekizai/blob/master/README.rst#documentation) in "Please refer to the documentation in the docs/ directory for more information or visit our online documentation.". 

The last listed Django version on the readthedocs site is 1.10.

**Comment by marksweb** [comment]
I've established the issue here. The RTD settings haven't been updated to reference the new location of the repo since it was moved under the django-cms organisation.

**Comment by marksweb** [comment]
I've updated the docs so they're building again.

https://django-sekizai.readthedocs.io/en/3.0.0/
