### ISSUE TITLE
Add support for Django 3.2

### ISSUE THREAD

**Issue by MaferMazu** [django-cms/django-sekizai#103]
In OpenedX the libraries are being upgraded to migrate to Django 3.2, I would like to add the necessary changes in the tests to ensure it.

I did a PR #102  , I would like to know your opinion and if something else is needed to support Django 3.2

**Comment by MaferMazu** [comment]
Thanks for the merge @marksweb . Do you plan to have a new **release** soon?

**Comment by marksweb** [comment]
You're welcome @MaferMazu

Unfortunately I can't release, but I have flagged the fact that this now needs a 3.2 compatible release, so hopefully we'll get one out soon.

**Comment by UsamaSadiq** [comment]
@marksweb since the release with `Django 3.2` support is already out, this issue can be closed.

**Comment by marksweb** [comment]
@UsamaSadiq The package hasn't actually been released yet. Last release for this app is 2020.

I'm in the process of getting these packages setup with release automation, but that requires fairly sensitive access to things so it's a slow process. It will however mean that once the correct pypi auth tokens are in place in the repos, releases to pypi will happen off the back of release creation in github.
