### ISSUE TITLE
3.0.0: Tests missing in sdist tarball on pypi.org

### ISSUE THREAD

**Issue by dvzrv** [django-cms/django-sekizai#115]
Hi! Upon trying to package version 3.0.0 for Arch Linux I noticed that the tests are still missing (see also https://github.com/django-cms/django-sekizai/issues/87#issuecomment-685938239).

Can they please be added? :)

**Comment by marksweb** [comment]
Ah I misunderstood your previous issue. I didn't realise you wanted the tests. I thought you were raising the fact they were included and causing problems!

**Comment by dvzrv** [comment]
> Ah I misunderstood your previous issue. I didn't realise you wanted the tests. I thought you were raising the fact they were included and causing problems!

I was raising the fact that they were installed as a module system-wide as well, but that is a separate issue (see also https://github.com/django-cms/django-classy-tags/issues/52#issuecomment-577638993 for an overview for django-classy-tags which has the same issue).

The files in the sdist tarball are configured via the [MANIFEST.in file](https://github.com/django-cms/django-sekizai/blob/f7ef98837db2da4e263e589079885fcf0be3b3f2/MANIFEST.in) in this project.
Which files are installed as modules is defined in the [setup.py file](https://github.com/django-cms/django-sekizai/blob/f7ef98837db2da4e263e589079885fcf0be3b3f2/setup.py#L50) of this project.

**Comment by marksweb** [comment]
@dvzrv Please try 3.0.1 which I've just released. Hopefully this has what you need.

**Comment by dvzrv** [comment]
Thanks! That works perfectly! :)
