### ISSUE TITLE
Django 4.2 support?

### ISSUE THREAD

**Issue by greyhare** [django-cms/django-sekizai#156]
Django 4.2 is released, but the `requirements.txt` files at root level and the `docs` dir lock to 4.0 or so. Also `CLASSIFIERS` in `setup.py` probably needs `'Framework :: Django :: 4.2',` added.

**Comment by marksweb** [comment]
Technically 4.0 will "just work" with 4.2.

However, I've just released 4.1.0 which explicit testing against 4.2 and django's main branch.

https://github.com/django-cms/django-sekizai/releases/tag/4.1.0
