### ISSUE TITLE
How to get Sekizai working in an InclusionTag 

### ISSUE THREAD

**Issue by guidors** [django-cms/django-sekizai#19]
Hi Ojii,

I have an issue with Sekizai on which I've spend already a lot of time. I've been trying to create a templatetag based on a template containing Sekizai addtoblock. However, all my attemps end with the error:

> You must enable the 'sekizai.context_processors.sekizai' template context processor or use 'sekizai.context.SekizaiContext' to render your templates.

Could you help me in the right direction? 

I created the templatetag polls_extras.py:

``` python
from django import template
from django.template.loader import render_to_string
from classytags.arguments import Argument
from classytags.core import Options
from classytags.helpers import InclusionTag

class show_results(InclusionTag):
    template = 'result_tag.html'

    options = Options(
        Argument('poll')
    )

    def get_context(self, context, poll):
        choices = poll.choice_set.all()
        return {'choices': choices}

    def render_tag(self, context, poll):
        print context
        return super(render_tag, self, context, poll)

    def render_tag(self, context, poll):
        data = self.get_context(context, poll)
        output = render_to_string(self.template, data)
        return output

register.tag(show_results)
```

and this is my result_tag.html:

``` django
{% load sekizai_tags %}
{% addtoblock "test" %}<br/>Some more Sekizai{% endaddtoblock %}
<ul>
{% for choice in choices %}
    <li> {{ choice }} </li>
{% endfor %}
</ul>
```

this is part of my base template:

``` django
{% load poll_extras sekizai_tags %}
<h1>{% render_block "test" %}</h1>
x
x
x
{% show_results poll %}
```

As you see I have created the render_tag function but I have no idea how to alter that to make it work. I guess there need to be two passes, one to put poll in the InclusionTag and then the whole base template needs to be rendered with the Sekizai directive. I've looked at django-cms where the toolbar is rendered as an Inclusion Tag without a problem. Could you indicate how this issue can be solved?

Thanks,

Guido

**Comment by laffuste** [comment]
Hi,

5 years Kate, bit here is another way to use sekizai inside the template of an inclusion tag:

https://stackoverflow.com/a/34080624/1297812
