### ISSUE TITLE
spaceless sekizai render_block

### ISSUE THREAD

**Issue by nrvnrvn** [django-cms/django-sekizai#30]
Hi!
When I wrap the template with `{% spaceless %}`, I get 500 error with `Invalid block tag: 'endspaceless'`
Thus, not to catch the exception I have to escape render_block tags like this:
`{% spaceless %}"Anything here"{% endspaceless %}
{% render_block "js" postprocessor "compressor.contrib.sekizai.compress" %}
{% spaceless %}The rest of template{% endspaceless %}`

**Comment by bittner** [comment]
@ojii The links about are now broken. Working links are:

http://django-sekizai.readthedocs.org/en/latest/index.html#restrictions
http://django-sekizai.readthedocs.org/en/latest/index.html#template-tag-reference
